file=$(find "${{ github.workspace }}/output/" -type f -name '*.iso' -print -quit 2>/dev/null)

fullpath="$file"
basename="${file##*/}"
name="${basename%.iso}"
timestamp=$(date +%Y%m%d%H%M%S)

echo "Full path: $fullpath"
echo "Basename:  $basename"
echo "Name:      $name"
echo "Timestamp: $timestamp"

cat << EOF > Dockerfile
FROM registry.access.redhat.com/ubi8/ubi:latest AS builder
ARG ARTIFACT_NAME
ADD --chown=107:107 \${ARTIFACT_NAME} /disk/image.qcow2

FROM scratch
COPY --from=builder /disk/* /disk/
EOF

docker build \
  -f Dockerfile \
  --build-arg "ARTIFACT_NAME=output/$basename" \
  -t "floatingcontainers/$name:$timestamp" \
  .
